### PR TITLE
Update README with official TS logo from branding team

### PR DESCRIPTION
**Pull request by jattasNI**
The branding team provided a lockup of the NI and TS logos. I'm adding it to the README alongside the existing JS logo.

Also changing to use HTML tags for these images because they support scaling the image to be smaller.

image

### CODE REVIEW

**Comment by rajsite** [comment]
Can we place them next to each, center them, and move them above the header line? It'll use less vertical space and I think it looks nice:

```markdown
<div align="center">
    <div>
        <!-- Load images from raw.githubusercontent.com to enable image rendering when viewed from https://www.npmjs.com/package/@ni/eslint-config -->
        <img src="https://raw.githubusercontent.com/ni/javascript-styleguide/HEAD/resources/ni-js-logo.svg" alt="JavaScript and NI logo" width="200px"> <img src="https://raw.githubusercontent.com/ni/javascript-styleguide/HEAD/resources/ni-ts-logo.svg" alt="TypeScript and NI logo" width="200px">
    </div>
</div>

# NI JavaScript and TypeScript Style Guide
```

image

**Review by TrevorKarjanis — CHANGES_REQUESTED** [review]
Multiple NI logos doesn't make sense and looks like a bug. If necessary, let's leave out TS.

**Comment by jattasNI** [comment]
I updated to use the new "NI | JS TS" logo and to center it above the header.

**Review by TrevorKarjanis — APPROVED** [review]
Awesome work!

**Review by rajsite — APPROVED** [review]
🎉

**Pull request merged**
